keys = [ 
	'vip_object.election ',
	'vip_object.election.absentee_ballot_info',
	'vip_object.election.absentee_request_deadline',
	'vip_object.election.date',
	'vip_object.election.election_day_registration',
	'vip_object.election.election_type',
	'vip_object.election.polling_hours',
	'vip_object.election.registration_deadline',
	'vip_object.election.registration_info',
	'vip_object.election.results_url',
	'vip_object.election.state_id',
	'vip_object.election.statewide',
	'vip_object.election_administration',
	'vip_object.election_administration.elections_url',
	'vip_object.election_administration.eo_id',
	'vip_object.election_administration.hours',
	'vip_object.election_administration.name',
	'vip_object.election_administration.physical_address',
	'vip_object.election_administration.physical_address.city',
	'vip_object.election_administration.physical_address.line1',
	'vip_object.election_administration.physical_address.line2',
	'vip_object.election_administration.physical_address.line3',
	'vip_object.election_administration.physical_address.state',
	'vip_object.election_administration.physical_address.zip',
	'vip_object.election_official',
	'vip_object.election_official.email',
	'vip_object.election_official.fax',
	'vip_object.election_official.name',
	'vip_object.election_official.phone',
	'vip_object.election_official.title',
	'vip_object.electoral_district',
	'vip_object.electoral_district.name',
	'vip_object.electoral_district.type',
	'vip_object.locality',
	'vip_object.locality.election_administration_id',
	'vip_object.locality.name',
	'vip_object.locality.state_id',
	'vip_object.locality.type',
	'vip_object.polling_location',
	'vip_object.polling_location.address',
	'vip_object.polling_location.address.city',
	'vip_object.polling_location.address.line1',
	'vip_object.polling_location.address.line2',
	'vip_object.polling_location.address.location_name',
	'vip_object.polling_location.address.state',
	'vip_object.polling_location.address.zip',
	'vip_object.precinct',
	'vip_object.precinct.locality_id',
	'vip_object.precinct.name',
	'vip_object.precinct_split',
	'vip_object.precinct_split.name',
	'vip_object.precinct_split.polling_location_id',
	'vip_object.precinct_split.precinct_id',
	'vip_object.source',
	'vip_object.source.datetime',
	'vip_object.source.description',
	'vip_object.source.feed_contact_id',
	'vip_object.source.name',
	'vip_object.source.organization_url',
	'vip_object.source.vip_id',
	'vip_object.state',
	'vip_object.state.name',
	'vip_object.street_segment',
	'vip_object.street_segment.end_house_number',
	'vip_object.street_segment.non_house_address',
	'vip_object.street_segment.non_house_address.address_direction',
	'vip_object.street_segment.non_house_address.city',
	'vip_object.street_segment.non_house_address.state',
	'vip_object.street_segment.non_house_address.street_direction',
	'vip_object.street_segment.non_house_address.street_name',
	'vip_object.street_segment.non_house_address.street_suffix',
	'vip_object.street_segment.non_house_address.zip',
	'vip_object.street_segment.odd_even_both',
	'vip_object.street_segment.precinct_id',
	'vip_object.street_segment.precinct_split_id',
	'vip_object.street_segment.start_house_number'
]


found_VA = [
((u'locality',
   ((u'election_administration_id', None),
    (u'id', None),
    (u'name', None),
    (u'state_id', None),
    (u'type', None))),),
 ((u'election_official', None),),
 ((u'eo_id', None),),
 ((u'polling_location',
   ((u'address',
     ((u'city', None),
      (u'line1', None),
      (u'line2', None),
      (u'location_name', None),
      (u'state', None),
      (u'zip', None))),
    (u'id', None))),),
 ((u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'line3', None),
    (u'state', None),
    (u'zip', None))),),
 ((u'name', None),),
 ((u'source',
   ((u'datetime', None),
    (u'description', None),
    (u'feed_contact_id', None),
    (u'id', None),
    (u'name', None),
    (u'organization_url', None),
    (u'vip_id', None))),),
 ((u'precinct_id', None),),
 ((u'street_segment',
   ((u'end_house_number', None),
    (u'id', None),
    (u'non_house_address',
     ((u'address_direction', None),
      (u'city', None),
      (u'state', None),
      (u'street_direction', None),
      (u'street_name', None),
      (u'street_suffix', None),
      (u'zip', None))),
    (u'odd_even_both', None),
    (u'precinct_id', None),
    (u'precinct_split_id', None),
    (u'start_house_number', None))),),
 ((u'state', None),),
 ((u'election',
   ((u'absentee_ballot_info', None),
    (u'absentee_request_deadline', None),
    (u'date', None),
    (u'election_day_registration', None),
    (u'election_type', None),
    (u'id', None),
    (u'polling_hours', None),
    (u'registration_deadline', None),
    (u'registration_info', None),
    (u'results_url', None),
    (u'state_id', None),
    (u'statewide', None))),),
 ((u'phone', None),),
 ((u'fax', None),),
 ((u'precinct_split', None),),
 ((u'type', None),),
 ((u'election_administration', None),),
 ((u'electoral_district', None),),
 ((u'elections_url', None),),
 ((u'email', None),),
 ((u'precinct', ((u'id', None), (u'locality_id', None), (u'name', None))),),
 ((u'polling_location_id', None),),
 ((u'hours', None),),
 ((u'title', None),),
 ((u'vip_object', None),)]


found_OH = [
 ((u'election_administration', None),
  (u'election_official',
   ((u'email', None),
    (u'fax', None),
    (u'id', None),
    (u'name', None),
    (u'phone', None))),
  (u'elections_url', None),
  (u'hours', None)),
 ((u'locality',
   ((u'election_administration_id', None),
    (u'id', None),
    (u'name', None),
    (u'state_id', None),
    (u'type', None))),),
 ((u'election_administration', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None)))),
 ((u'election_administration', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None), (u'line1', None), (u'state', None), (u'zip', None)))),
 ((u'election_administration', None),
  (u'elections_url', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None)))),
 ((u'source',
   ((u'datetime', None),
    (u'description', None),
    (u'id', None),
    (u'name', None),
    (u'organization_url', None),
    (u'vip_id', None))),),
 ((u'election_official',
   ((u'email', None),
    (u'fax', None),
    (u'id', None),
    (u'name', None),
    (u'phone', None))),),
 ((u'election_administration', None),
  (u'elections_url', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None), (u'line1', None), (u'state', None), (u'zip', None)))),
 ((u'polling_location',
   ((u'address',
     ((u'city', None),
      (u'line1', None),
      (u'location_name', None),
      (u'state', None),
      (u'zip', None))),
    (u'id', None))),),
 ((u'eo_id', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None)))),
 ((u'polling_location',
   ((u'address',
     ((u'city', None),
      (u'line1', None),
      (u'location_name', None),
      (u'state', None),
      (u'zip', None))),
    (u'directions', None),
    (u'id', None))),),
 ((u'precinct',
   ((u'id', None),
    (u'locality_id', None),
    (u'name', None),
    (u'number', None),
    (u'polling_location_id', None))),),
 ((u'mailing_address',
   ((u'city', None), (u'line1', None), (u'state', None), (u'zip', None))),),
 ((u'street_segment',
   ((u'end_house_number', None),
    (u'id', None),
    (u'non_house_address',
     ((u'city', None),
      (u'state', None),
      (u'street_name', None),
      (u'zip', None))),
    (u'odd_even_both', None),
    (u'precinct_id', None),
    (u'start_house_number', None))),),
 ((u'mailing_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None))),),
 ((u'election',
   ((u'date', None),
    (u'election_type', None),
    (u'id', None),
    (u'state_id', None),
    (u'statewide', None))),)]


if __name__ == "__main__":
	import IPython
	IPython.embed()
