#was using these data structures to generate more useful mapping data structures
#file can probably be tossed now

keys = [ 
	'election ',
	'election.absentee_ballot_info',
	'election.absentee_request_deadline',
	'election.date',
	'election.election_day_registration',
	'election.election_type',
	'election.polling_hours',
	'election.registration_deadline',
	'election.registration_info',
	'election.results_url',
	'election.state_id',
	'election.statewide',
	'election_administration',
	'election_administration.elections_url',
	'election_administration.eo_id',
	'election_administration.hours',
	'election_administration.name',
	'election_administration.physical_address',
	'election_administration.physical_address.city',
	'election_administration.physical_address.line1',
	'election_administration.physical_address.line2',
	'election_administration.physical_address.line3',
	'election_administration.physical_address.state',
	'election_administration.physical_address.zip',
	'election_official',
	'election_official.email',
	'election_official.fax',
	'election_official.name',
	'election_official.phone',
	'election_official.title',
	'electoral_district',
	'electoral_district.name',
	'electoral_district.type',
	'locality',
	'locality.election_administration_id',
	'locality.name',
	'locality.state_id',
	'locality.type',
	'polling_location',
	'polling_location.address',
	'polling_location.address.city',
	'polling_location.address.line1',
	'polling_location.address.line2',
	'polling_location.address.location_name',
	'polling_location.address.state',
	'polling_location.address.zip',
	'precinct',
	'precinct.locality_id',
	'precinct.name',
	'precinct_split',
	'precinct_split.name',
	'precinct_split.polling_location_id',
	'precinct_split.precinct_id',
	'source',
	'source.datetime',
	'source.description',
	'source.feed_contact_id',
	'source.name',
	'source.organization_url',
	'source.vip_id',
	'state',
	'state.name',
	'street_segment',
	'street_segment.end_house_number',
	'street_segment.non_house_address',
	'street_segment.non_house_address.address_direction',
	'street_segment.non_house_address.city',
	'street_segment.non_house_address.state',
	'street_segment.non_house_address.street_direction',
	'street_segment.non_house_address.street_name',
	'street_segment.non_house_address.street_suffix',
	'street_segment.non_house_address.zip',
	'street_segment.odd_even_both',
	'street_segment.precinct_id',
	'street_segment.precinct_split_id',
	'street_segment.start_house_number'
]


found_VA = [
((u'locality',
   ((u'election_administration_id', None),
    (u'id', None),
    (u'name', None),
    (u'state_id', None),
    (u'type', None))),),
 ((u'election_official', None),),
 ((u'eo_id', None),),
 ((u'polling_location',
   ((u'address',
     ((u'city', None),
      (u'line1', None),
      (u'line2', None),
      (u'location_name', None),
      (u'state', None),
      (u'zip', None))),
    (u'id', None))),),
 ((u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'line3', None),
    (u'state', None),
    (u'zip', None))),),
 ((u'name', None),),
 ((u'source',
   ((u'datetime', None),
    (u'description', None),
    (u'feed_contact_id', None),
    (u'id', None),
    (u'name', None),
    (u'organization_url', None),
    (u'vip_id', None))),),
 ((u'precinct_id', None),),
 ((u'street_segment',
   ((u'end_house_number', None),
    (u'id', None),
    (u'non_house_address',
     ((u'address_direction', None),
      (u'city', None),
      (u'state', None),
      (u'street_direction', None),
      (u'street_name', None),
      (u'street_suffix', None),
      (u'zip', None))),
    (u'odd_even_both', None),
    (u'precinct_id', None),
    (u'precinct_split_id', None),
    (u'start_house_number', None))),),
 ((u'state', None),),
 ((u'election',
   ((u'absentee_ballot_info', None),
    (u'absentee_request_deadline', None),
    (u'date', None),
    (u'election_day_registration', None),
    (u'election_type', None),
    (u'id', None),
    (u'polling_hours', None),
    (u'registration_deadline', None),
    (u'registration_info', None),
    (u'results_url', None),
    (u'state_id', None),
    (u'statewide', None))),),
 ((u'phone', None),),
 ((u'fax', None),),
 ((u'precinct_split', None),),
 ((u'type', None),),
 ((u'election_administration', None),),
 ((u'electoral_district', None),),
 ((u'elections_url', None),),
 ((u'email', None),),
 ((u'precinct', ((u'id', None), (u'locality_id', None), (u'name', None))),),
 ((u'polling_location_id', None),),
 ((u'hours', None),),
 ((u'title', None),),
 ((u'vip_object', None),)]


found_OH = [
 ((u'election_administration', None),
  (u'election_official',
   ((u'email', None),
    (u'fax', None),
    (u'id', None),
    (u'name', None),
    (u'phone', None))),
  (u'elections_url', None),
  (u'hours', None)),
 ((u'locality',
   ((u'election_administration_id', None),
    (u'id', None),
    (u'name', None),
    (u'state_id', None),
    (u'type', None))),),
 ((u'election_administration', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None)))),
 ((u'election_administration', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None), (u'line1', None), (u'state', None), (u'zip', None)))),
 ((u'election_administration', None),
  (u'elections_url', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None)))),
 ((u'source',
   ((u'datetime', None),
    (u'description', None),
    (u'id', None),
    (u'name', None),
    (u'organization_url', None),
    (u'vip_id', None))),),
 ((u'election_official',
   ((u'email', None),
    (u'fax', None),
    (u'id', None),
    (u'name', None),
    (u'phone', None))),),
 ((u'election_administration', None),
  (u'elections_url', None),
  (u'eo_id', None),
  (u'hours', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None), (u'line1', None), (u'state', None), (u'zip', None)))),
 ((u'polling_location',
   ((u'address',
     ((u'city', None),
      (u'line1', None),
      (u'location_name', None),
      (u'state', None),
      (u'zip', None))),
    (u'id', None))),),
 ((u'eo_id', None),
  (u'name', None),
  (u'physical_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None)))),
 ((u'polling_location',
   ((u'address',
     ((u'city', None),
      (u'line1', None),
      (u'location_name', None),
      (u'state', None),
      (u'zip', None))),
    (u'directions', None),
    (u'id', None))),),
 ((u'precinct',
   ((u'id', None),
    (u'locality_id', None),
    (u'name', None),
    (u'number', None),
    (u'polling_location_id', None))),),
 ((u'mailing_address',
   ((u'city', None), (u'line1', None), (u'state', None), (u'zip', None))),),
 ((u'street_segment',
   ((u'end_house_number', None),
    (u'id', None),
    (u'non_house_address',
     ((u'city', None),
      (u'state', None),
      (u'street_name', None),
      (u'zip', None))),
    (u'odd_even_both', None),
    (u'precinct_id', None),
    (u'start_house_number', None))),),
 ((u'mailing_address',
   ((u'city', None),
    (u'line1', None),
    (u'line2', None),
    (u'state', None),
    (u'zip', None))),),
 ((u'election',
   ((u'date', None),
    (u'election_type', None),
    (u'id', None),
    (u'state_id', None),
    (u'statewide', None))),)]


keys_via_data_model = [
  'election.id',
  'election.date',
  'election.election_type',
  'election.state_id',
  'election.statewide',
  'election.registration_info',
  'election.absentee_ballot_info',
  'election.results_url',
  'election.polling_hours',
  'election.election_day_registration',
  'election.registration_deadline',
  'election.absentee_request_deadline',
  'election.PRIMARY',
  'contest.id',
  'contest.election_id',
  'contest.electoral_district_id',
  'contest.partisan',
  'contest.type',
  'contest.primary_party',
  'contest.electorate_specifications',
  'contest.special',
  'contest.office',
  'contest.filing_closed_date',
  'contest.number_elected',
  'contest.number_voting_for',
  'contest.ballot_placement',
  'contest.contest_type',
  'contest.write_in',
  'contest.custom_ballot_heading',
  'contest.PRIMARY',
  'candidate.id',
  'candidate.name',
  'candidate.party',
  'candidate.candidate_url',
  'candidate.biography',
  'candidate.phone',
  'candidate.photo_url',
  'candidate.filed_mailing_address',
  'candidate.email',
  'candidate.incumbent',
  'candidate.google_plus_url',
  'candidate.twitter_name',
  'candidate.facebook_url',
  'candidate.wiki_word',
  'candidate.PRIMARY',
  'referendum.id',
  'referendum.title',
  'referendum.subtitle',
  'referendum.brief',
  'referendum.text',
  'referendum.pro_statement',
  'referendum.con_statement',
  'referendum.contest_id',
  'referendum.passage_threshold',
  'referendum.effect_of_abstain',
  'referendum.PRIMARY',
  'ballot_response.id',
  'ballot_response.contest_id',
  'ballot_response.sort_order',
  'ballot_response.text',
  'ballot_response.PRIMARY',
  'candidate_in_contest.sort_order',
  'candidate_in_contest.contest_id',
  'candidate_in_contest.candidate_id',
  'candidate_in_contest.PRIMARY',
  'source.id',
  'source.user_id',
  'source.source_data_file_url',
  'source.hash',
  'source.aquired',
  'source.reviewed',
  'source.reviewing_user_id',
  'source.PRIMARY',
  'precinct.id',
  'precinct.name',
  'precinct.number',
  'precinct.electoral_district',
  'precinct.ward',
  'precinct.mail_only',
  'precinct.polling_location_id',
  'precinct.early_vote_site_id',
  'precinct.ballot_style_image_url',
  'precinct.election_administration_id',
  'precinct.state_id',
  'precinct.PRIMARY',
  'electoral_district.id',
  'electoral_district.name',
  'electoral_district.type',
  'electoral_district.number',
  'electoral_district.PRIMARY',
  'street_segment.id',
  'street_segment.start_house_number',
  'street_segment.end_house_number',
  'street_segment.odd_even_both',
  'street_segment.start_apartment_number',
  'street_segment.end_apartment_number',
  'street_segment.non_house_address',
  'street_segment.precinct_id',
  'street_segment.PRIMARY',
  'street_segment.CONSTRAINT',
  'geo_cd.id',
  'geo_cd.electoral_district_id',
  'geo_cd.PRIMARY',
  'electoral_district__precinct.electoral_district_id',
  'electoral_district__precinct.precinct_id',
  'electoral_district__precinct.PRIMARY',
  'org_custom_field.parent_id',
  'org_custom_field.key',
  'org_custom_field.value',
  'org_custom_field.type',
  'org_custom_field.org_id',
  'org_custom_field.PRIMARY',
  'election_administration.id',
  'election_administration.name',
  'election_administration.ovc_id',
  'election_administration.eo_id',
  'election_administration.physical_address',
  'election_administration.mailing_address',
  'election_administration.elections_url',
  'election_administration.type',
  'election_administration.state_id',
  'election_administration.hours',
  'election_administration.voter_services',
  'election_administration.rules_url',
  'election_administration.what_is_on_my_ballot_url',
  'election_administration.where_do_i_vote_url',
  'election_administration.absentee_url',
  'election_administration.am_i_registered_url',
  'election_administration.registration_url',
  'election_administration.PRIMARY',
  'state.id',
  'state.name',
  'state.postal_code',
  'state.PRIMARY',
  'state.CONSTRAINT',
  'state.CONSTRAINT',
  'precinct__early_vote_site.precinct_id',
  'precinct__early_vote_site.early_vote_site_id',
  'precinct__early_vote_site.PRIMARY',
  'early_vote_site.id',
  'early_vote_site.name',
  'early_vote_site.address',
  'early_vote_site.directions',
  'early_vote_site.voter_services',
  'early_vote_site.start_date',
  'early_vote_site.end_date',
  'early_vote_site.state_id',
  'early_vote_site.days_time_open',
  'early_vote_site.PRIMARY',
  'polling_location.id',
  'polling_location.address',
  'polling_location.directions',
  'polling_location.polling_hours',
  'polling_location.photo_url',
  'polling_location.PRIMARY',
  'precinct__polling_location.precinct_id',
  'precinct__polling_location.polling_location_id',
  'precinct__polling_location.PRIMARY',
  'geo_county.id',
  'geo_county.electoral_district_id',
  'geo_county.PRIMARY',
  'geo_ss.id',
  'geo_ss.electoral_district_id',
  'geo_ss.PRIMARY',
  'geo_sh.id',
  'geo_sh.electoral_district_id',
  'geo_sh.PRIMARY',
  'geo_address.id',
  'geo_address.is_standardized',
  'geo_address.is_geocoded',
  'geo_address.house_number',
  'geo_address.house_number_prefix',
  'geo_address.hosue_number_suffix',
  'geo_address.street_direction',
  'geo_address.location_name',
  'geo_address.line3',
  'geo_address.line2',
  'geo_address.line1',
  'geo_address.city',
  'geo_address.state',
  'geo_address.zip4',
  'geo_address.zip',
  'geo_address.xcoord',
  'geo_address.ycoord',
  'geo_address.apartment',
  'geo_address.PRIMARY',
  'election_official.id',
  'election_official.title',
  'election_official.phone',
  'election_official.fax',
  'election_official.email',
  'election_official.name',
  'election_official.PRIMARY'
]



if __name__ == "__main__":
	import IPython
	IPython.embed()
